SHOW DATABASES

CREATE DATABASE CECIL

USE CECIL

CREATE TABLE EMPLOYE(
ID INT PRIMARY KEY,
EMP_NAME VARCHAR (50),
SALARY INT)

INSERT INTO EMPLOYE
VALUES
(1, "ANIDA",40000),
(2, "ANNU", 34000),
(3, "BANCY", 63000),
(4, "CALISTA", 43000),
(5, "DALLY", 34500),
(6, "EMMY", 45000),
(7, "FRED", 55000)

CREATE TABLE RECYCLE (
ID INT, 
EMP_NAME VARCHAR (50),
SALARY INT, 
DELETED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP)

DELIMITER //
CREATE TRIGGER DELETED_DATA
AFTER DELETE 
ON 
EMPLOYE
FOR EACH ROW 
BEGIN 
INSERT INTO RECYCLE (ID, EMP_NAME, SALARY)
VALUES
(OLD.ID, OLD.EMP_NAME, OLD.SALARY);
END//
DELIMITER ; 

DELETE FROM EMPLOYE 
WHERE ID = 3

SELECT * FROM RECYCLE 

SELECT * FROM EMPLOYE

USE CECIL

CREATE TABLE VISITORS(
SR INT PRIMARY KEY,
V_NAME VARCHAR (40),
FLOOR_NO INT,
DEPT VARCHAR (20),
REASON VARCHAR (50))

INSERT INTO VISITORS
VALUES
(1,"NAMRATA",2,"HR","INTERVIEW"),
(2,"MANVITA",1,"MARKETING","SALES"),
(3,"OMKAR",3,"IT","SETTING UP WIFI"),
(4,"PRANAV",6,"IT","SET CAMERA'S"),
(5,"QWALLIN",4,"HR","ROUTINE CHECK"),
(6,"RHEA",10,"HM","CANTEEN SERVICE")

CREATE TABLE RECYCLE_BIN(
SR INT,
V_NAME VARCHAR (40),
FLOOR_NO INT,
DEPT VARCHAR (20),
REASON VARCHAR (50))

DELIMITER $
CREATE TRIGGER DELETE_DATA
AFTER DELETE ON VISITORS
FOR EACH ROW BEGIN
INSERT INTO RECYCLE_BIN (SR, V_NAME, FLOOR_NO, DEPT, REASON)
VALUES
(OLD.SR, OLD.V_NAME, OLD.FLOOR_NO, OLD.DEPT, OLD.REASON);
END $
DELIMITER ;

DELETE FROM VISITORS
WHERE V_NAME = "PRANAV"

SELECT * FROM VISITORS

SET SQL_SAFE_UPDATES=0
